// MobileGlues - diagnostics/instrumented_gl.cpp
// Copyright (c) 2025-2026 MobileGL-Dev
// Licensed under the GNU Lesser General Public License v2.1:
//   https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
// SPDX-License-Identifier: LGPL-2.1-only
// End of Source File Header

// GL entry points that forward straight to the driver but are timed on the way through.
//
// These three would normally be generated by the NATIVE_FUNCTION_HEAD macro in gl/gl_native.cpp
// like their neighbours. They live here instead because they are the calls whose cost has to be
// measured to understand a driver's memory and synchronization behaviour, and writing them out
// inside that file would mean adding hand-written code into a dense block of macro invocations
// that clang-format cannot reason about. Keeping them in their own translation unit leaves the
// generated block untouched and keeps this code readable and formatted.
//
// Behaviour is identical to the generated wrappers: same signature, same ARB alias, same error
// check, same forwarding. Only the timing is added, and it is inert unless diagnostics are on.

#include "../includes.h"

#include <GL/gl.h>

#include "../gl/glcorearb.h"
#include "../gl/log.h"
#include "../gl/mg.h"
#include "../gles/loader.h"
#include "counters.h"
#if defined(MG_PLATFORM_OHOS)
// For the copy-destination probe below: the shadow binding lookup and the per-buffer flag.
#include "../gl/buffer.h"
#endif

// Per-file verbosity switch, as in every other translation unit here: the logging macros test it.
#define DEBUG 0

// Uploads into an existing buffer. Worth measuring because the driver may synchronize implicitly
// here, which turns a call that looks like a memory copy into a wait.
#if !defined(__APPLE__)
extern "C" GLAPI GLAPIENTRY void glBufferSubDataARB(GLenum target, GLintptr offset, GLsizeiptr size, const void* data)
    __attribute__((alias("glBufferSubData")));
#endif
extern "C" GLAPI GLAPIENTRY void glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const void* data) {
    LOG_D("Use native function: %s @ %s(...)", RENDERERNAME, __FUNCTION__);
#if defined(MG_PLATFORM_OHOS)
    // Ordering: an ordinary ordered write must not overtake a queued one, or the application's own
    // sequence of updates to the same range would be applied out of order. Range-scoped, because a
    // per-buffer test on the terrain heaps fires constantly for no reason - see
    // mg_deferred_upload_flush_if_range.
    if (mg_deferred_upload_pending()) {
        mg_deferred_upload_flush_if_range(mg_real_buffer_for_target(target), offset, size);
    }
#endif
    const uint64_t startNs = mg::diagnostics::timestamp();
    GLES.glBufferSubData(target, offset, size, data);
    mg::diagnostics::record_sub_data(mg::diagnostics::non_negative_bytes(size), mg::diagnostics::elapsed_ns(startNs));
    CHECK_GL_ERROR
}

// Buffer-to-buffer copies, which is how an application's staging buffer reaches its destination.
// On some drivers the read side of this copy is far slower than its size suggests.
#if !defined(__APPLE__)
extern "C" GLAPI GLAPIENTRY void glCopyBufferSubDataARB(GLenum readTarget, GLenum writeTarget, GLintptr readOffset,
                                                        GLintptr writeOffset, GLsizeiptr size)
    __attribute__((alias("glCopyBufferSubData")));
#endif
extern "C" GLAPI GLAPIENTRY void glCopyBufferSubData(GLenum readTarget, GLenum writeTarget, GLintptr readOffset,
                                                     GLintptr writeOffset, GLsizeiptr size) {
    LOG_D("Use native function: %s @ %s(...)", RENDERERNAME, __FUNCTION__);
#if defined(MG_PLATFORM_OHOS)
    // Probe only, no behaviour change: remember that this destination receives GPU-side copies.
    // See gl/buffer.h. The destination is read from the shadow binding rather than the driver, so
    // this costs an array lookup and no round trip. Unconditional rather than gated on diagnostics
    // because the flag has to be accurate from the first copy, and a diagnostics session that starts
    // later would otherwise see an empty table.
    mark_buffer_copy_destination(find_bound_buffer(GL_COPY_WRITE_BUFFER_BINDING));

    // A copy can read a queued range as its source, or write one as its destination. Either way the
    // queue has to land first - but only if the ranges actually meet.
    //
    // This used to be an unconditional flush_all, and that was the sprint-flight frame collapse.
    // Sodium issues 186-210 copies per second from its mapped ring into the same arena that its
    // ring-overflow writes are queued against, so a per-buffer or unconditional test fired on
    // essentially every copy - and the fence being waited on had been taken microseconds earlier in
    // the same tryUploads batch, so the poll failed and a full pipeline drain was paid. About 40-50
    // CPU/GPU serializations per second, which is the shape docs/ohos/RENDER-ADAPTATION.md already
    // measured at 261-454 ms/s and rejected. Vanilla never showed it because vanilla barely copies.
    //
    // Every pending upload owns a separately allocated arena segment, so the range test below
    // should essentially never fire; deferred_forced_flush says whether that holds.
    if (mg_deferred_upload_pending()) {
        mg_deferred_upload_flush_if_range(mg_real_buffer_for_target(readTarget), readOffset, size);
        mg_deferred_upload_flush_if_range(mg_real_buffer_for_target(writeTarget), writeOffset, size);
    }
#endif
    const uint64_t startNs = mg::diagnostics::timestamp();
    GLES.glCopyBufferSubData(readTarget, writeTarget, readOffset, writeOffset, size);
    mg::diagnostics::record_copy(mg::diagnostics::non_negative_bytes(size), mg::diagnostics::elapsed_ns(startNs));
    CHECK_GL_ERROR
}

// The application waiting on its own fences. Recorded with the result and whether a timeout was
// requested, because a zero-timeout poll that returns already-signalled and a blocking wait that
// times out are opposite findings.
#if !defined(__APPLE__)
extern "C" GLAPI GLAPIENTRY GLenum glClientWaitSyncARB(GLsync sync, GLbitfield flags, GLuint64 timeout)
    __attribute__((alias("glClientWaitSync")));
#endif
extern "C" GLAPI GLAPIENTRY GLenum glClientWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout) {
    LOG_D("Use native function: %s @ %s(...)", RENDERERNAME, __FUNCTION__);
    const uint64_t startNs = mg::diagnostics::timestamp();
    const GLenum result = GLES.glClientWaitSync(sync, flags, timeout);
    mg::diagnostics::record_sync_wait(result, timeout, mg::diagnostics::elapsed_ns(startNs));
    CHECK_GL_ERROR
    return result;
}
